Public Class TableUserData
    Public Const id As String = "id"
    Public Const nik As String = "nik"
    Public Const user_id As String = "user_id"
    Public Const name As String = "name"
    Public Const tempat_lahir As String = "tempat_lahir"
    Public Const tanggal_lahir As String = "tanggal_lahir"
    Public Const jenis_kelamin As String = "jenis_kelamin"
    Public Const alamat As String = "alamat"
    Public Const rt_rw As String = "rt_rw"
    Public Const kel_desa As String = "kel_desa"
    Public Const kecamatan As String = "kecamatan"
    Public Const agama As String = "agama"
    Public Const st_kawin As String = "st_kawin"
    Public Const pekerjaan As String = "pekerjaan"
    Public Const kewarganegaraan As String = "kewarganegaraan"
    Public Const exp As String = "exp"
    Public Const img As String = "img"
End Class
